In [6]:
from sqlalchemy import create_engine, Column, String, Integer, Float, DateTime
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

# Define the connection string
postgres_url = "postgresql+psycopg2://postgres:example@192.168.2.34:5432/app_db"

# Create the SQLAlchemy engine
engine = create_engine(postgres_url, echo=True)

# Define the declarative base
Base = declarative_base()

# Define the stock_price_training table
class StockPriceTraining(Base):
    __tablename__ = 'stock_price_training'

    # Define columns
    date_time = Column(DateTime, primary_key=True)
    stock_id = Column(String, nullable=False)
    open = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    adj_close = Column(Float, nullable=False)
    volume = Column(Integer, nullable=False)
    currency = Column(String, nullable=False)

    def __repr__(self):
        return (f"<StockPriceTraining(date_time={self.date_time}, stock_id='{self.stock_id}', "
                f"open={self.open}, close={self.close}, high={self.high}, low={self.low}, "
                f"adj_close={self.adj_close}, currency='{self.currency}')>")

# Create all tables in the engine (here, it creates the stock_price_training table)
Base.metadata.create_all(engine)

print("Table 'stock_price_training' created successfully.")

2025-04-29 04:16:35,288 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2025-04-29 04:16:35,289 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-04-29 04:16:35,292 INFO sqlalchemy.engine.Engine select current_schema()
2025-04-29 04:16:35,292 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-04-29 04:16:35,295 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2025-04-29 04:16:35,295 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-04-29 04:16:35,298 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-04-29 04:16:35,299 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-04-29 04:16:35,300 INFO sqlalchemy.engine.Engine [generated in 0.00028s] {'table_name': 'stock_price_training', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-04-29 04:16:35,304 INFO sqlalchemy.engine.Engine
CREATE TABLE stock_price_training (
	date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	stock_id VARCHAR NOT NULL,
	open FLOAT NOT NULL,
	close FLOAT NOT NULL,
	high FLOAT NOT NULL,
	low FLOAT NOT NULL,
	adj_close FLOAT NOT NULL,
	volume INTEGER NOT NULL,
	currency VARCHAR NOT NULL,
	PRIMARY KEY (date_time)
)


2025-04-29 04:16:35,305 INFO sqlalchemy.engine.Engine [no key 0.00031s] {}

2025-04-29 04:16:35,316 INFO sqlalchemy.engine.Engine COMMIT
Table 'stock_price_training' created successfully.

/tmp/ipykernel_2671708/1702822469.py:12: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

In [5]:
# iterate over the folder ../training_data, find out all text files
import os
import glob
import pandas as pd
from datetime import datetime
from sqlalchemy.orm import sessionmaker
import yfinance as yfin

# Create a session
Session = sessionmaker(bind=engine)
session = Session()
# Define the path to the training data folder
training_data_folder = '../training_data'
# Get a list of all text files in the training data folder
text_files = glob.glob(os.path.join(training_data_folder, '*.txt'))
# Iterate over each text file
text_file = '../../training_data/dax_40.txt'
  # read the stock_id from the file, one stock_id per line, and make a list of all stock_ids
with open(text_file, 'r') as f:
  stock_ids = [line.strip() for line in f.readlines()]
print(stock_ids)

stock_id = stock_ids[0]

data = yfin.Ticker(stock_id).history(start='1950-01-01', end=None, auto_adjust=False, timeout=40)
data.index = data.index.date.astype(str)
print(data)

['ADS.DE', 'AIR.DE', 'ALV.DE', 'BAS.DE', 'BAYN.DE', 'BEI.DE', 'BMW.DE', 'BNR.DE', 'CBK.DE', 'CON.DE', '1COV.DE', 'DTG.DE', 'DBK.DE', 'DB1.DE', 'DHL.DE', 'DTE.DE', 'EOAN.DE', 'FRE.DE', 'HNR1.DE', 'HEI.DE', 'HEN3.DE', 'IFX.DE', 'MBG.DE', 'MRK.DE', 'MTX.DE', 'MUV2.DE', 'P911.DE', 'PAH3.DE', 'QIA.DE', 'RHM.DE', 'RWE.DE', 'SAP.DE', 'SRT3.DE', 'SIE.DE', 'ENR.DE', 'SHL.DE', 'SY1.DE', 'VOW3.DE', 'VNA.DE', 'ZAL.DE']
                  Open        High         Low       Close   Adj Close  \
1998-06-24   40.916248   41.159000   40.775501   40.775501   28.966839
1998-06-25   41.146252   41.286751   40.622250   40.647751   28.876081
1998-06-26   40.647751   40.673248   39.880749   39.925499   28.362993
1998-06-29   40.136501   40.520000   40.136501   40.424000   28.717131
1998-06-30   40.634998   40.634998   39.433498   39.631500   28.154137
...                ...         ...         ...         ...         ...
2025-04-22  200.899994  204.500000  198.699997  204.199997  204.199997
2025-04-23  208.000000  214.399994  207.100006  210.300003  210.300003
2025-04-24  214.500000  217.899994  212.000000  215.600006  215.600006
2025-04-25  216.100006  219.500000  214.600006  217.000000  217.000000
2025-04-28  216.199997  219.600006  216.100006  217.399994  217.399994

            Volume  Dividends  Stock Splits
1998-06-24  181816        0.0           0.0
1998-06-25  263828        0.0           0.0
1998-06-26  239488        0.0           0.0
1998-06-29  184268        0.0           0.0
1998-06-30  312500        0.0           0.0
...            ...        ...           ...
2025-04-22  677292        0.0           0.0
2025-04-23  696950        0.0           0.0
2025-04-24  719453        0.0           0.0
2025-04-25  558166        0.0           0.0
2025-04-28  422492        0.0           0.0

[6870 rows x 8 columns]

In [2]:
text_file = '../../training_data/sp_500.txt'

with open(text_file, 'r') as f:
    stock_ids = [line.replace(' ', '-').strip() for line in f.readlines()]
    print(stock_ids)

['MMM', 'AOS', 'ABT', 'ABBV', 'ACN', 'ADBE', 'AMD', 'AES', 'AFL', 'A', 'APD', 'ABNB', 'AKAM', 'ALB', 'ARE', 'ALGN', 'ALLE', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AMCR', 'AEE', 'AAL', 'AEP', 'AXP', 'AIG', 'AMT', 'AWK', 'AMP', 'AME', 'AMGN', 'APH', 'ADI', 'ANSS', 'AON', 'APA', 'AAPL', 'AMAT', 'APTV', 'ACGL', 'ADM', 'ANET', 'AJG', 'AIZ', 'T', 'ATO', 'ADSK', 'ADP', 'AZO', 'AVB', 'AVY', 'AXON', 'BKR', 'BALL', 'BAC', 'BK', 'BBWI', 'BAX', 'BDX', 'BRK.B', 'BBY', 'BIO', 'TECH', 'BIIB', 'BLK', 'BX', 'BA', 'BKNG', 'BWA', 'BXP', 'BSX', 'BMY', 'AVGO', 'BR', 'BRO', 'BF.B', 'BLDR', 'BG', 'CDNS', 'CZR', 'CPT', 'CPB', 'COF', 'CAH', 'KMX', 'CCL', 'CARR', 'CTLT', 'CAT', 'CBOE', 'CBRE', 'CDW', 'CE', 'COR', 'CNC', 'CNP', 'CF', 'CHRW', 'CRL', 'SCHW', 'CHTR', 'CVX', 'CMG', 'CB', 'CHD', 'CI', 'CINF', 'CTAS', 'CSCO', 'C', 'CFG', 'CLX', 'CME', 'CMS', 'KO', 'CTSH', 'CL', 'CMCSA', 'CMA', 'CAG', 'COP', 'ED', 'STZ', 'CEG', 'COO', 'CPRT', 'GLW', 'CPAY', 'CTVA', 'CSGP', 'COST', 'CTRA', 'CCI', 'CSX', 'CMI', 'CVS', 'DHR', 'DRI', 'DVA', 'DAY', 'DECK', 'DE', 'DAL', 'DVN', 'DXCM', 'FANG', 'DLR', 'DFS', 'DG', 'DLTR', 'D', 'DPZ', 'DOV', 'DOW', 'DHI', 'DTE', 'DUK', 'DD', 'EMN', 'ETN', 'EBAY', 'ECL', 'EIX', 'EW', 'EA', 'ELV', 'LLY', 'EMR', 'ENPH', 'ETR', 'EOG', 'EPAM', 'EQT', 'EFX', 'EQIX', 'EQR', 'ESS', 'EL', 'ETSY', 'EG', 'EVRG', 'ES', 'EXC', 'EXPE', 'EXPD', 'EXR', 'XOM', 'FFIV', 'FDS', 'FICO', 'FAST', 'FRT', 'FDX', 'FIS', 'FITB', 'FSLR', 'FE', 'FI', 'FMC', 'F', 'FTNT', 'FTV', 'FOXA', 'FOX', 'BEN', 'FCX', 'GRMN', 'IT', 'GE', 'GEHC', 'GEV', 'GEN', 'GNRC', 'GD', 'GIS', 'GM', 'GPC', 'GILD', 'GPN', 'GL', 'GS', 'HAL', 'HIG', 'HAS', 'HCA', 'DOC', 'HSIC', 'HSY', 'HES', 'HPE', 'HLT', 'HOLX', 'HD', 'HON', 'HRL', 'HST', 'HWM', 'HPQ', 'HUBB', 'HUM', 'HBAN', 'HII', 'IBM', 'IEX', 'IDXX', 'ITW', 'ILMN', 'INCY', 'IR', 'PODD', 'INTC', 'ICE', 'IFF', 'IP', 'IPG', 'INTU', 'ISRG', 'IVZ', 'INVH', 'IQV', 'IRM', 'JBHT', 'JBL', 'JKHY', 'J', 'JNJ', 'JCI', 'JPM', 'JNPR', 'K', 'KVUE', 'KDP', 'KEY', 'KEYS', 'KMB', 'KIM', 'KMI', 'KLAC', 'KHC', 'KR', 'LHX', 'LH', 'LRCX', 'LW', 'LVS', 'LDOS', 'LEN', 'LIN', 'LYV', 'LKQ', 'LMT', 'L', 'LOW', 'LULU', 'LYB', 'MTB', 'MRO', 'MPC', 'MKTX', 'MAR', 'MMC', 'MLM', 'MAS', 'MA', 'MTCH', 'MKC', 'MCD', 'MCK', 'MDT', 'MRK', 'META', 'MET', 'MTD', 'MGM', 'MCHP', 'MU', 'MSFT', 'MAA', 'MRNA', 'MHK', 'MOH', 'TAP', 'MDLZ', 'MPWR', 'MNST', 'MCO', 'MS', 'MOS', 'MSI', 'MSCI', 'NDAQ', 'NTAP', 'NFLX', 'NEM', 'NWSA', 'NWS', 'NEE', 'NKE', 'NI', 'NDSN', 'NSC', 'NTRS', 'NOC', 'NCLH', 'NRG', 'NUE', 'NVDA', 'NVR', 'NXPI', 'ORLY', 'OXY', 'ODFL', 'OMC', 'ON', 'OKE', 'ORCL', 'OTIS', 'PCAR', 'PKG', 'PANW', 'PARA', 'PH', 'PAYX', 'PAYC', 'PYPL', 'PNR', 'PEP', 'PFE', 'PCG', 'PM', 'PSX', 'PNW', 'PXD', 'PNC', 'POOL', 'PPG', 'PPL', 'PFG', 'PG', 'PGR', 'PLD', 'PRU', 'PEG', 'PTC', 'PSA', 'PHM', 'QRVO', 'PWR', 'QCOM', 'DGX', 'RL', 'RJF', 'RTX', 'O', 'REG', 'REGN', 'RF', 'RSG', 'RMD', 'RVTY', 'RHI', 'ROK', 'ROL', 'ROP', 'ROST', 'RCL', 'SPGI', 'CRM', 'SBAC', 'SLB', 'STX', 'SRE', 'NOW', 'SHW', 'SPG', 'SWKS', 'SJM', 'SNA', 'SOLV', 'SO', 'LUV', 'SWK', 'SBUX', 'STT', 'STLD', 'STE', 'SYK', 'SMCI', 'SYF', 'SNPS', 'SYY', 'TMUS', 'TROW', 'TTWO', 'TPR', 'TRGP', 'TGT', 'TEL', 'TDY', 'TFX', 'TER', 'TSLA', 'TXN', 'TXT', 'TMO', 'TJX', 'TSCO', 'TT', 'TDG', 'TRV', 'TRMB', 'TFC', 'TYL', 'TSN', 'USB', 'UBER', 'UDR', 'ULTA', 'UNP', 'UAL', 'UPS', 'URI', 'UNH', 'UHS', 'VLO', 'VTR', 'VLTO', 'VRSN', 'VRSK', 'VZ', 'VRTX', 'VTRS', 'VICI', 'V', 'VMC', 'WRB', 'WAB', 'WBA', 'WMT', 'DIS', 'WBD', 'WM', 'WAT', 'WEC', 'WFC', 'WELL', 'WST', 'WDC', 'WRK', 'WY', 'WMB', 'WTW', 'GWW', 'WYNN', 'XEL', 'XYL', 'YUM', 'ZBRA', 'ZBH', 'ZTS']

In [5]:
import yfinance as yf
multi = yf.Tickers(stock_ids)
hist  = multi.history(start="2023-01-01", auto_adjust=False, timeout=40)
# hist is either a Panel-like object or a dict of DataFrames, one per ticker

[*********************100%***********************]  503 of 503 completed

6 Failed downloads:
['MRO', 'CTLT', 'WRK']: YFPricesMissingError('possibly delisted; no price data found  (1d 2023-01-01 -> 2025-05-01) (Yahoo error = "No data found, symbol may be delisted")')
['BF.B']: YFPricesMissingError('possibly delisted; no price data found  (1d 2023-01-01 -> 2025-05-01)')
['BRK.B', 'PXD']: YFTzMissingError('possibly delisted; no timezone found')

In [4]:
hist

Price        Adj Close                                                         \
Ticker               A    AAL        AAPL        ABBV        ABNB         ABT
Date
1962-01-02         NaN    NaN         NaN         NaN         NaN         NaN
1962-01-03         NaN    NaN         NaN         NaN         NaN         NaN
1962-01-04         NaN    NaN         NaN         NaN         NaN         NaN
1962-01-05         NaN    NaN         NaN         NaN         NaN         NaN
1962-01-08         NaN    NaN         NaN         NaN         NaN         NaN
...                ...    ...         ...         ...         ...         ...
2025-04-25  106.279999   9.75  209.279999  186.059998  122.510002  128.850006
2025-04-28  106.870003   9.85  210.139999  192.339996  123.300003  129.529999
2025-04-29  107.459999   9.90  211.210007  193.509995  125.489998  130.500000
2025-04-30  107.599998   9.95  212.500000  195.100006  121.919998  130.750000
2025-05-01  106.459999  10.03  213.320007  193.339996  124.010002  130.880005

Price                                                      ...     Volume  \
Ticker           ACGL         ACN        ADBE         ADI  ...        WTW
Date                                                       ...
1962-01-02        NaN         NaN         NaN         NaN  ...        NaN
1962-01-03        NaN         NaN         NaN         NaN  ...        NaN
1962-01-04        NaN         NaN         NaN         NaN  ...        NaN
1962-01-05        NaN         NaN         NaN         NaN  ...        NaN
1962-01-08        NaN         NaN         NaN         NaN  ...        NaN
...               ...         ...         ...         ...  ...        ...
2025-04-25  90.680000  293.390015  367.720001  194.589996  ...  1557400.0
2025-04-28  91.190002  293.250000  368.619995  193.720001  ...   804300.0
2025-04-29  92.389999  298.470001  370.980011  192.669998  ...   586500.0
2025-04-30  90.680000  299.149994  374.980011  194.919998  ...   710200.0
2025-05-01  89.669998  300.529999  374.630005  193.740005  ...   576960.0

Price                                                                        \
Ticker             WY       WYNN        XEL       XOM        XYL        YUM
Date
1962-01-02        NaN        NaN        NaN    902400        NaN        NaN
1962-01-03        NaN        NaN        NaN   1200000        NaN        NaN
1962-01-04        NaN        NaN        NaN   1088000        NaN        NaN
1962-01-05        NaN        NaN        NaN   1222400        NaN        NaN
1962-01-08        NaN        NaN        NaN   1388800        NaN        NaN
...               ...        ...        ...       ...        ...        ...
2025-04-25  4584400.0  1467700.0  4816800.0  11245800  1923100.0  1770400.0
2025-04-28  7708600.0  1443300.0  2994500.0  13890900  2427200.0  2218800.0
2025-04-29  5244800.0  1463600.0  2539300.0   9483100  2864900.0  2339600.0
2025-04-30  5015900.0  1922700.0  4468300.0  20379300  2701500.0  3349500.0
2025-05-01  2785962.0  1707996.0  3067597.0  14015627  1260075.0  1968937.0

Price
Ticker            ZBH       ZBRA        ZTS
Date
1962-01-02        NaN        NaN        NaN
1962-01-03        NaN        NaN        NaN
1962-01-04        NaN        NaN        NaN
1962-01-05        NaN        NaN        NaN
1962-01-08        NaN        NaN        NaN
...               ...        ...        ...
2025-04-25  1662000.0   530200.0  3543600.0
2025-04-28  1299600.0  1094500.0  1873400.0
2025-04-29   925700.0  1599800.0  2065100.0
2025-04-30  1399600.0   762600.0  2926200.0
2025-05-01  1023381.0   506569.0  1920079.0

[15940 rows x 4012 columns]

In [ ]:
import yfinance as yfin
import pandas as pd
import os
import glob
from sqlalchemy import create_engine, Column, String, Float, DateTime
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from sqlalchemy import PrimaryKeyConstraint  # Import for composite primary key


# --- Database Setup (Same as before, needed to define the table) ---
# Define the connection string
postgres_url = "postgresql+psycopg2://postgres:example@192.168.2.34:5432/app_db"  # replace with your correct URL

# Create the SQLAlchemy engine
engine = create_engine(postgres_url, echo=True)

# Define the declarative base
Base = declarative_base()

# Define the stock_price_training table with date_time and stock_id as primary keys
class StockPriceTraining(Base):
    __tablename__ = 'stock_price_training'

    date_time = Column(DateTime, nullable=False)
    stock_id = Column(String, nullable=False)
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    adj_close = Column(Float, nullable=False)
    volume = Column(Float, nullable=False) # added volume
    currency = Column(String, nullable=False, default="USD")  # Added currency and default value


    __table_args__ = (
        PrimaryKeyConstraint('date_time', 'stock_id'),
    )

    def __repr__(self):
        return (f"<StockPriceTraining(date_time={self.date_time}, stock_id='{self.stock_id}', "
                f"open={self.open}, close={self.close}, high={self.high}, low={self.low}, "
                f"adj_close={self.adj_close}, volume={self.volume}, currency='{self.currency}')>")

# Create the table if it doesn't exist
Base.metadata.create_all(engine)

# --- Data Import Section ---

# Create a session
Session = sessionmaker(bind=engine)
session = Session()

# Define the path to the training data folder
training_data_folder = '../../training_data' # Ensure the path is relative correctly

text_files = glob.glob(os.path.join(training_data_folder, '*.txt'))

for text_file in text_files:
    currency = "USD"  # Default currency
    if 'dax' in text_file:
        currency = "EUR"
    elif 'omx' in text_file:
        currency = "SEK"
    elif 'cac' in text_file:
        currency = "EUR"
    elif 'ftse' in text_file:
        currency = "GBP"

    # read the stock_id from the file, one stock_id per line, and make a list of all stock_ids
    with open(text_file, 'r') as f:
        stock_ids = [line.replace(' ', '-').strip() for line in f.readlines()]
        print(stock_ids)


    # loop through each stock_id and fetch the data then insert the data into the database.
    for stock_id in stock_ids:
        try:
            data = yfin.Ticker(stock_id).history(start='1950-01-01', end=None, auto_adjust=False, timeout=40)
            data.index = pd.to_datetime(data.index)  # Convert index to datetime objects
            # Convert volume to numeric
            data['Volume'] = pd.to_numeric(data['Volume'], errors='coerce')  # Handle potential errors

            if not data.empty:
                for index, row in data.iterrows(): # iterate through dataframe rows
                    # Create a StockPriceTraining object for each row
                    new_entry = StockPriceTraining(
                        date_time=index,
                        stock_id=stock_id,
                        open=row['Open'],
                        close=row['Close'],
                        high=row['High'],
                        low=row['Low'],
                        adj_close=row['Adj Close'],
                        volume=row['Volume'],
                        currency=currency
                    )
                    session.add(new_entry) # add the new entry to the session

                session.commit() # commit changes to the database
                print(f"Successfully imported data for {stock_id}")

        except Exception as e:
            print(f"Error importing data for {stock_id}: {e}")
            session.rollback() # Rollback in case of error


session.close()  # Close the session when done